### ISSUE TITLE
"NameError: name 'as_completed' is not defined" raised

### ISSUE THREAD

**Issue by kconkas** [hrcorval/behavex#146]
**Describe the bug**
"NameError: name 'as_completed' is not defined" is raised when trying to run 2 parallel processes at feature level. This behaviour happens since 4.0.4 (4.0.2 is unaffected).

**To Reproduce**
1. Run ` behavex  --parallel-processes 2 --parallel-scheme feature --no_capture --no_logcapture`
2. Observe the error raised

Full stack trace is:
```
************************************************************
Running parallel features.
************************************************************

Traceback (most recent call last):
  File "/Users/myuser/.pyenv/versions/3.10.10/envs/fangtooth-3.10.10/bin/behavex", line 8, in <module>
    sys.exit(main())
  File "/Users/myuser/.pyenv/versions/3.10.10/envs/fangtooth-3.10.10/lib/python3.10/site-packages/behavex/runner.py", line 81, in main
    exit_code = run(args)
  File "/Users/myuser/.pyenv/versions/3.10.10/envs/fangtooth-3.10.10/lib/python3.10/site-packages/behavex/runner.py", line 138, in run
    return launch_behavex()
  File "/Users/myuser/.pyenv/versions/3.10.10/envs/fangtooth-3.10.10/lib/python3.10/site-packages/behavex/runner.py", line 258, in launch_behavex
    execution_codes, json_reports = launch_by_feature(updated_features_list,
  File "/Users/myuser/.pyenv/versions/3.10.10/envs/fangtooth-3.10.10/lib/python3.10/site-packages/behavex/runner.py", line 498, in launch_by_feature
    for parallel_process in as_completed(parallel_processes):
NameError: name 'as_completed' is not defined
```

**Expected behavior**
No exception is raised, 2 parallel executions start and run to completion.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
The issue doesn't seem to be OS-specific, reproduced (so far) on Linux and MacOS.

**Comment by hrcorval** [comment]
Hi @kconkas , thanks for reporting this. It seems that as part of a configuration management issue we lost a change in that line of code when merging the implementations. The issue should be fixed in v4.0.5 that is already released. We apologize for any inconvenience.
